name: OTT Project CI/CD Pipeline

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ "main" ]

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3. Install Dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Basic Import Check (CI)
    - name: Validate Imports
      run: |
        python -c "import pandas, numpy, sklearn, gradio, fastapi; print('All imports successful ✅')"

    # 5. Project Structure Check
    - name: Verify Project Structure
      run: |
        echo "Project structure:"
        ls -R

    # 6. Docker Build (CD simulation)
    - name: Build Docker Image
      run: |
        docker build -t ott-churn-app .

    # 7. Final Success Message
    - name: Pipeline Status
      run: echo "CI/CD Pipeline executed successfully "